### ISSUE TITLE
search results page appears unconditionally in search results

### ISSUE THREAD

**Issue by mithat** [infostreams/pagelist-snippet#4]
I don't know if I'm abusing the intended use case for this plugin, but I'm attempting to use it to create a search feature for a site I'm developing. I have a page `search.md`:

``` markdown
<!--
Title: Search
Description: Search results
Robots: noindex,nofollow
-->

Search results
==============

(pagelist: search)
```

When I access this page with a query `http://sitename.com/search?q=keyword`, the URL `http://sitename.com/search` is returned in the results. To see what I mean live, try accessing http://audio.mithatkonar.com/search?q=remote. (Note that the search box at the top is currently configured for searching with Switftype, not this plugin). If the plugin finds any matches, then `http://audio.mithatkonar.com/search` itself is included in the results list.

The `pagelist-default.html` template I'm using is:

``` twig
<div class="row">
  <div class="col-md-8">
    {% for p in pagelist %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <a href="{{base_url}}/{{p.url}}">{{p.title}}</a>
      </div>
      <div class="panel-body">
{#      <p>{{p.meta.description}}</p> #}
        <p>{{p.content|striptags|slice(0, 200)}} &hellip;</p>
      </div>
    </div>
  {% endfor %}
  </div>
</div>
```

Help?

**Comment by mithat** [comment]
As a workaround, I created a `Nosearch` meta, set it to true for the search page, and updated `pagelist-default.html` as follows:

``` twig
<div class="row">
  <div class="col-md-8">
  {% for p in pagelist %}
    {% if not p.meta.nosearch %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <a href="{{base_url}}/{{p.url}}">{{p.title}}</a>
        </div>
        <div class="panel-body">
          <p>{{p.meta.description}}</p>
{#        <p>{{p.content|striptags|slice(0, 200)}} &hellip;</p> #}
        </div>
      </div>
    {% endif %}
  {% endfor %}
  </div>
</div>

```

It would be nice if the workaround wasn't needed.

**Comment by infostreams** [comment]
That's not such a bad workaround, though. 

The issue was that the plugin would try to extract text from every page on the site, and to do that it has to render each page. That means that the search page itself would also be rendered, and the search page would (erroneously) run the search _again_, with the keyword you were looking for. That would produce a  results page containing the results of the search, which would then be indexed and searched and... since it would contain the keyword, it would turn up in the final list of results. It was a recursion bug, so to speak. I've fixed it and released a new version (1.0.4) which would allow you to remove the workaround. Can you check if that works for you?

**Comment by infostreams** [comment]
Also, you reporting this bug made the search much quicker, since it doesn't unnecessarily do this recursive searching anymore. So, thanks!

**Comment by mithat** [comment]
Works for me. :-) Thanks. You can close this as far as I'm concerned.

**Comment by infostreams** [comment]
Great!
