### ISSUE TITLE
Php Fatal Error

### ISSUE THREAD

**Issue by bglaz** [infostreams/pagelist-snippet#6]
Got this error when trying to load the plugin:

Fatal error: Cannot use Phile\Core\Event as Event because the name is already in use in /staging/webshares/pico/www/lib/Phile/Core.php on line 7

**Comment by infostreams** [comment]
Hi! This is probably related to [this PhileCMS issue](https://github.com/PhileCMS/Phile/issues/234). Do you get the error in the Snippets plugin or in the PagelistSnippet plugin? If it's in the Snippets plugin: it should be fixed in the most recent version. If it's in the PagelistSnippets plugin: can you send me the file + line number? I will then have a look at it soon (probably only on Monday though).

**Comment by bglaz** [comment]
It's in the PagelistSnippet plugin.

In the Plugin.php file I changed this code:

```
\Phile\Event::registerEvent('request_uri', $this);
\Phile\Event::registerEvent('template_engine_registered', $this);
\Phile\Event::registerEvent('plugins_loaded', $this);
```

To use `\Phile\Core\Event` instead, and that solved the issue.

```
\Phile\Core\Event::registerEvent('request_uri', $this);
\Phile\Core\Event::registerEvent('template_engine_registered', $this);
\Phile\Core\Event::registerEvent('plugins_loaded', $this);
```

However it's really strange, because `\Phile\Event\` is just an empty class that extends `\Phile\Core\Event` so I don't know why it would cause any issues.

**Comment by infostreams** [comment]
Yeah, it's because something in Phile 1.5 broke backwards compatibility. I pushed a new version of the plugin to both Github and Composer that should fix this. Can you update and let me know if that works?

**Comment by bglaz** [comment]
Yup, works as expected. Thanks!
